{- | Generators for the codec's round trips.

A constant is generated by picking its type first and then a value of that
type, so its type tags always match what is inside. Terms are generated
knowing how many lambdas enclose them, so every variable refers to one of
them. Shrinking keeps both of these true.
-}
module Cardano.UPLC.Test.Gen (
  Encodable (Encodable),
  Nested (Nested),
) where

import Data.ByteString qualified as BS
import Data.Text qualified as T
import Data.Word (Word64)
import Test.QuickCheck (
  Arbitrary (arbitrary, shrink),
  Gen,
  arbitraryBoundedEnum,
  choose,
  elements,
  listOf,
  oneof,
  scale,
  shrinkList,
  sized,
 )
import Cardano.UPLC.Constant (Constant (..))
import Cardano.UPLC.Name (DeBruijn (DeBruijn))
import Cardano.UPLC.Term (Program (Program), Term (..), Version (Version))
import Cardano.UPLC.Ty (Ty (..))

{- | A program the codec can take a round trip on: well-scoped, without
@data@ constants, at version 1.0.0 or 1.1.0. Below 1.1.0 the term has no
@constr@ or @case@, since the decoder refuses them there.
-}
newtype Encodable = Encodable (Program DeBruijn)
  deriving stock (Eq, Show)

instance Arbitrary Encodable where
  arbitrary = do
    version <- elements [Version 1 0 0, Version 1 1 0]
    Encodable . Program version <$> genTerm (version >= Version 1 1 0) 0
  shrink (Encodable (Program v t)) = Encodable . Program v <$> shrinkTerm 0 t

{- | A constant whose type is nested up to four levels deep, each depth
equally likely. The usual size-based generator hardly ever produces deep
types like a pair of lists of pairs, and those are what test the type
tags.
-}
newtype Nested = Nested Constant
  deriving stock (Eq, Show)

instance Arbitrary Nested where
  arbitrary = do
    depth <- choose (0 :: Int, 4)
    Nested <$> genConstant depth
  shrink (Nested c) = Nested <$> shrinkConstant c

-- A term with the given number of binders in scope. Var only appears where
-- the depth allows it, and the depth rises by one under every LamAbs.
genTerm :: Bool -> Word64 -> Gen (Term DeBruijn)
genTerm constrCase depth = sized (go depth)
  where
    go :: Word64 -> Int -> Gen (Term DeBruijn)
    go d size
      | size <= 0 = oneof (leaves d)
      | otherwise = oneof (leaves d <> branches d)

    leaves :: Word64 -> [Gen (Term DeBruijn)]
    leaves d =
      [ pure Error
      , Constant <$> (genConstant =<< choose (0, 2))
      , Builtin <$> arbitraryBoundedEnum
      ]
        <> [Var . DeBruijn <$> choose (1, d) | d > 0]

    -- DeBruijn 0 in a binder position is a placeholder: the wire carries
    -- nothing there, and no Var refers to it.
    branches :: Word64 -> [Gen (Term DeBruijn)]
    branches d =
      [ LamAbs (DeBruijn 0) <$> half (d + 1)
      , Apply <$> half d <*> half d
      , Delay <$> half d
      , Force <$> half d
      ]
        <> [ Constr <$> arbitrary <*> scaleDown (listOf (half d)) | constrCase ]
        <> [ Case <$> half d <*> scaleDown (listOf (half d)) | constrCase ]

    half :: Word64 -> Gen (Term DeBruijn)
    half d = scale (`quot` 2) (genTerm constrCase d)

-- A lambda's body is only shrunk in place, one deeper, so no variable is
-- left pointing past the binder it referred to.
shrinkTerm :: Word64 -> Term DeBruijn -> [Term DeBruijn]
shrinkTerm d = \case
  Var (DeBruijn i) -> [Var (DeBruijn j) | j <- shrink i, j >= 1]
  Constant c -> Constant <$> shrinkConstant c
  Builtin f -> Builtin <$> takeWhile (< f) [minBound ..]
  Error -> []
  Delay t -> t : (Delay <$> shrinkTerm d t)
  Force t -> t : (Force <$> shrinkTerm d t)
  LamAbs n t -> LamAbs n <$> shrinkTerm (d + 1) t
  Apply f x ->
    [f, x]
      <> [Apply f' x | f' <- shrinkTerm d f]
      <> [Apply f x' | x' <- shrinkTerm d x]
  Constr t xs -> xs <> (Constr t <$> shrinkList (shrinkTerm d) xs)
  Case s xs ->
    (s : xs)
      <> [Case s' xs | s' <- shrinkTerm d s]
      <> (Case s <$> shrinkList (shrinkTerm d) xs)

-- A type exactly this deep, together with a generator for its values, so
-- the two always match. No TyData, whose values need a CBOR codec, and no
-- BLS types, whose values flat never carries.
genWire :: Int -> Gen (Ty, Gen Constant)
genWire depth
  | depth <= 0 =
      elements
        [ (TyInteger, CInteger <$> arbitrary)
        , (TyByteString, CByteString . BS.pack <$> listOf arbitrary)
        , (TyString, CString . T.pack <$> listOf genChar)
        , (TyUnit, pure CUnit)
        , (TyBool, CBool <$> arbitrary)
        ]
  | otherwise =
      oneof
        [ do
            (t, g) <- sub
            pure (TyList t, CList t <$> scaleDown (listOf g))
        , do
            (t, g) <- sub
            pure (TyArray t, CArray t <$> scaleDown (listOf g))
        , do
            (a, ga) <- sub
            (b, gb) <- sub
            pure (TyPair a b, CPair a b <$> ga <*> gb)
        ]
  where
    sub :: Gen (Ty, Gen Constant)
    sub = genWire (depth - 1)

genConstant :: Int -> Gen Constant
genConstant depth = snd =<< genWire depth

-- Only the contents shrink. Shrinking a type would leave a constant whose
-- tags no longer match its value.
shrinkConstant :: Constant -> [Constant]
shrinkConstant = \case
  CInteger i -> CInteger <$> shrink i
  CByteString bs -> CByteString . BS.pack <$> shrink (BS.unpack bs)
  CString t -> CString . T.pack <$> shrink (T.unpack t)
  CUnit -> []
  CBool b -> CBool <$> shrink b
  CList t xs -> CList t <$> shrinkList shrinkConstant xs
  CArray t xs -> CArray t <$> shrinkList shrinkConstant xs
  CPair a b x y ->
    [CPair a b x' y | x' <- shrinkConstant x]
      <> [CPair a b x y' | y' <- shrinkConstant y]
  CData _ -> []

-- Characters of several UTF-8 lengths, since strings are encoded as UTF-8.
genChar :: Gen Char
genChar = elements $ ['a' .. 'z'] <> "\xe9\x3bb\x20ac\x65e5\x10348"

scaleDown :: Gen a -> Gen a
scaleDown = scale (`quot` 4)
